//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Book
    {
        public int SID { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
    }
}
